### PR TITLE
Fix defaults for NameShowOptions and NameScanOptions

### LINKED ISSUE #4: ncdns v0.0.10 - failed to query namecoin
With the latest version of ncdns (v0.0.10) attempting to look up a .bit domain gives a SERVFAIL. ncdns, when not forked, shows this message:

> [ERROR] ncdns.backend: failed to query namecoin: -1: name_show "name"
> 
> (the help entry for name_show follows)

No problems with ncdns v0.0.9.

### PR DESCRIPTION
**Pull request by JeremyRand**
Fixes https://github.com/namecoin/ncbtcjson/issues/4

### CODE REVIEW

**Comment by JeremyRand** [comment]
@redblade7 Could you please try this patch and check:

1. Whether it fixes old Namecoin Core compatibility.
2. Whether it still works with the latest Namecoin Core.

Thanks.

**Comment by redblade7** [comment]
I'm sorry, but I've never compiled the source for ncdns before. I never understood the instructions and remember getting it wrong the only time I tried, so I just always used the ncdns release binaries.

**Comment by JeremyRand** [comment]
Ok, no worries, I'll dig up an old 0.13.99-name-tab-beta1 installation here and see if I can test it locally.

**Comment by JeremyRand** [comment]
Okay, that was slightly trickier than I was expecting, but this should fix the situation now.  Will merge shortly, and then tag new releases and build new binaries.

**Comment by JeremyRand** [comment]
@redblade7 v0.0.10.3 binaries are up on GitHub, can you try those and see if they fix your issue?

**Pull request merged**
