### PR TITLE
check nil before deref

### LINKED ISSUE #6: panic while running ncdumpzone
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4459b07]

goroutine 1 [running]:
github.com/namecoin/ncbtcjson.NewNameScanCmd(...)
	/Users/darren/Sources/go/pkg/mod/github.com/namecoin/ncbtcjson@v0.0.2/namecmds.go:86
github.com/namecoin/ncrpcclient.(*Client).NameScanAsync(0xc0000a20f0, 0x45c0801, 0x2, 0x3e8, 0x8)
	/Users/darren/Sources/go/pkg/mod/github.com/namecoin/ncrpcclient@v0.0.1/names.go:106 +0x67
github.com/namecoin/ncrpcclient.(*Client).NameScan(0xc0000a20f0, 0x45c0801, 0x2, 0xc0000003e8, 0xc0000a20f0, 0xc00021fe88, 0x4459112, 0xc00021fe88, 0x400f368)
	/Users/darren/Sources/go/pkg/mod/github.com/namecoin/ncrpcclient@v0.0.1/names.go:112 +0x4b
github.com/namecoin/ncdns/ncdumpzone.Dump(0xc0000a20f8, 0x4799620, 0xc0000a2008, 0x45c2097, 0x8, 0x4799260, 0xc000155aa0)
	/Users/darren/Sources/go/src/github.com/namecoin/ncdns/ncdumpzone/ncdumpzone.go:97 +0x279
main.main()
	/Users/darren/Sources/go/src/github.com/namecoin/ncdns/ncdumpzone/ncdumpzone/ncdumpzone.go:63 +0x35b
```

### PR DESCRIPTION
**Pull request by darren**
This pr fixes #6

### CODE REVIEW

**Comment by JeremyRand** [comment]
@darren Could you squash the `go fmt` fix into the previous commit?

**Comment by darren** [comment]
@JeremyRand 
Done! Does it look good now?

**Comment by JeremyRand** [comment]
@darren It looks like `NewNameShowCmd` has the same bug.  Could you make the same change there for consistency?

**Comment by JeremyRand** [comment]
utACK the code changes for c3125a4fb620682251368008e99ba6345a6b3c7e.  @darren Can you revise the commit message for 8ba2715b76d6ec2755edf861a0dde0d5472f7063 (that commit is for `NameScanOptions` but the commit message incorrectly says `NameShowOptions`)?

**Comment by JeremyRand** [comment]
@darren Okay, last thing: the commit message for 92b501ec3a0ed5c36efe9c1c1caee8cf97a57fbf has a tab between "deref" and "for"; can you change that to a space?  Once that's done, I think we'll be ready to merge this.

**Comment by JeremyRand** [comment]
utACK 4e4fc485df9d1bd65531070d2f362391123b8682.  Thanks for the PR, merging shortly.

**Pull request merged**
